# This is just a sample file. For a fully documented version of this file, see
# https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/files/tool_list.yaml.sample
api_key: admin
galaxy_instance: http://127.0.0.1:8080/
tools:
## LCMS
#LCMS-preprocessing
- name: xcms_xcmsset
  owner: lecorguille
  tool_panel_section_id: 'LCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
- name: xcms_group
  owner: lecorguille
  tool_panel_section_id: 'LCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
- name: xcms_retcor
  owner: lecorguille
  tool_panel_section_id: 'LCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
- name: xcms_fillpeaks
  owner: lecorguille
  tool_panel_section_id: 'LCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
- name: camera_annotate
  owner: lecorguille
  tool_panel_section_id: 'LCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
- name: xcms_summary
  owner: lecorguille
  tool_panel_section_id: 'LCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
- name: camera_combinexsannos
  owner: mmonsoor
  tool_panel_section_id: 'LCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
#- name: hca
#  owner: lecorguille
#  tool_panel_section_id: 'LCMS-statistical_analysis'
#  tool_shed_url: https://toolshed.g2.bx.psu.edu
#  install_tool_dependencies: False
#  install_resolver_dependencies: True
#LCMS-statistical_analysis

#LCMS-quality_control
- name: qualitymetrics
  owner: ethevenot
  tool_panel_section_id: 'LCMS-quality_control'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True

#LCMS-annotation
- name: probmetab
  owner: mmonsoor
  tool_panel_section_id: 'LCMS-annotation'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
- name: lcmsmatching
  owner: prog
  tool_panel_section_id: 'LCMS-annotation'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True

## GCMS
#GCMS-preprocessing
- name: metams_rungc
  owner: yguitton
  tool_panel_section_id: 'GCMS-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True

## NMR
#NMR-preprocessing
- name: nmr_bucketing
  owner: marie-tremblay-metatoul
  tool_panel_section_id: 'NMR-preprocessing'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
#NMR-normalisation
- name: nmr_normalization
  owner: marie-tremblay-metatoul
  tool_panel_section_id: 'NMR-normalisation'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True

## COMMON
#*-normalisation
- name: batchcorrection
  owner: melpetera
  tool_panel_section_id: 'LCMS-normalisation'
  tool_panel_section_id_alts: 
    - 'LCMS-normalisation'
    - 'GCMS-normalisation'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
- name: transformation
  owner: ethevenot
  tool_panel_section_id: 'LCMS-normalisation'
  tool_panel_section_id_alts: 
    - 'LCMS-normalisation'
    - 'GCMS-normalisation'
    - 'NMR-normalisation'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True

#*-statistical_analysis
- name: anova
  owner: lecorguille
  tool_panel_section_id: 'LCMS-statistical_analysis'
  tool_panel_section_id_alts: 
    - 'LCMS-statistical_analysis'
    - 'GCMS-statistical_analysis'
    - 'NMR-statistical_analysis'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
- name: heatmap
  owner: ethevenot
  tool_panel_section_id: 'LCMS-statistical_analysis'
  tool_panel_section_id_alts: 
    - 'LCMS-statistical_analysis'
    - 'GCMS-statistical_analysis'
    - 'NMR-statistical_analysis'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
- name: univariate
  owner: ethevenot
  tool_panel_section_id: 'LCMS-statistical_analysis'
  tool_panel_section_id_alts: 
    - 'LCMS-statistical_analysis'
    - 'GCMS-statistical_analysis'
    - 'NMR-statistical_analysis'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
- name: multivariate
  owner: ethevenot
  tool_panel_section_id: 'LCMS-statistical_analysis'
  tool_panel_section_id_alts: 
    - 'LCMS-statistical_analysis'
    - 'GCMS-statistical_analysis'
    - 'NMR-statistical_analysis'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
- name: biosigner
  owner: ethevenot
  tool_panel_section_id: 'LCMS-statistical_analysis'
  tool_panel_section_id_alts: 
    - 'LCMS-statistical_analysis'
    - 'GCMS-statistical_analysis'
    - 'NMR-statistical_analysis'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True


#W4M-Data-Handling
- name: checkformat
  owner: ethevenot
  tool_panel_section_id: 'W4M-Data-Handling'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  install_tool_dependencies: False
  install_resolver_dependencies: True
